/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import {
  Badge,
  Button,
  Divider,
  Flex,
  Image,
  SelectField,
  Text,
  TextField,
  View,
} from "@aws-amplify/ui-react";
import MyIcon from "./MyIcon";
export default function FormCheckout(props) {
  const { overrides: overridesProp, ...rest } = props;
  const overrides = { ...overridesProp };
  return (
    <Flex
      gap="24px"
      direction="row"
      width="1160px"
      alignItems="flex-start"
      position="relative"
      padding="0px 0px 0px 0px"
      {...rest}
      {...getOverrideProps(overrides, "Flex")}
    >
      <Flex
        gap="0"
        direction="row"
        width="667px"
        alignItems="flex-start"
        grow="1"
        basis="667px"
        height="1150px"
        position="relative"
        padding="32px 0px 32px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Flex.Flex[0]")}
      >
        <Flex
          gap="32px"
          direction="column"
          width="667px"
          justifyContent="center"
          alignItems="center"
          grow="1"
          basis="667px"
          height="1086px"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0]")}
        >
          <Flex
            gap="24px"
            direction="column"
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            position="relative"
            padding="0px 32px 0px 32px"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Flex[0]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="20px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Info"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[0].Text[0]"
              )}
            ></Text>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[0].TextField[0]"
              )}
            ></TextField>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[0].TextField[1]"
              )}
            ></TextField>
          </Flex>
          <Divider
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Divider[0]")}
          ></Divider>
          <Flex
            gap="24px"
            direction="column"
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            position="relative"
            padding="0px 32px 0px 32px"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Flex[1]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="20px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Shipping"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].Text[0]"
              )}
            ></Text>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].TextField[0]"
              )}
            ></TextField>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].TextField[1]"
              )}
            ></TextField>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].TextField[2]"
              )}
            ></TextField>
          </Flex>
          <Divider
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Divider[1]")}
          ></Divider>
          <Flex
            gap="24px"
            direction="column"
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            position="relative"
            padding="0px 32px 0px 32px"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Flex[2]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="20px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Card info"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].Text[0]"
              )}
            ></Text>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].TextField[0]"
              )}
            ></TextField>
            <TextField
              gap="12px"
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              label="Label"
              placeholder="Placeholder"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].TextField[1]"
              )}
            ></TextField>
            <Flex
              gap="24px"
              direction="row"
              alignItems="flex-start"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              position="relative"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].Flex[0]"
              )}
            >
              <SelectField
                gap="12px"
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="88px"
                label="Label"
                placeholder="Placeholder"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[2].Flex[0].SelectField[0]"
                )}
              ></SelectField>
              <SelectField
                gap="12px"
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="88px"
                label="Label"
                placeholder="Placeholder"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[2].Flex[0].SelectField[1]"
                )}
              ></SelectField>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
      <Flex
        gap="10px"
        direction="row"
        width="fit-content"
        alignItems="flex-start"
        shrink="0"
        height="933px"
        position="relative"
        padding="32px 0px 32px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Flex.Flex[1]")}
      >
        <Flex
          padding="0px 0px 0px 0px"
          width="469px"
          height="869px"
          shrink="0"
          position="relative"
          {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0]")}
        >
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="137.5px"
            position="absolute"
            top="194px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[0]")}
          >
            <Image
              position="absolute"
              top="0%"
              bottom="5.45%"
              height="94.55%"
              left="0%"
              right="78.02%"
              width="21.98%"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].Image[0]"
              )}
            ></Image>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              position="absolute"
              top="81.45%"
              bottom="1.09%"
              left="29.88%"
              right="39.51%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Order Summary"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(92,102,112,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="23.27%"
              bottom="59.27%"
              left="29.88%"
              right="59.75%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Black"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].Text[1]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="82.55%"
              left="29.88%"
              right="51.85%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Basic Tee"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].Text[2]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(92,102,112,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="46.55%"
              bottom="36%"
              left="29.88%"
              right="59.26%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Large"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].Text[3]"
              )}
            ></Text>
            <MyIcon
              position="absolute"
              top="0%"
              bottom="82.55%"
              left="94.07%"
              right="0%"
              type="delete"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].MyIcon[0]"
              )}
            ></MyIcon>
            <SelectField
              width="64px"
              position="absolute"
              display="flex"
              top="73.09%"
              bottom="0%"
              left="84.2%"
              right="0%"
              placeholder=""
              size="small"
              labelHidden={true}
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[0].SelectField[0]"
              )}
            ></SelectField>
          </View>
          <Divider
            position="absolute"
            top="41.66%"
            bottom="58.23%"
            left="0%"
            right="0%"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Divider[0]")}
          ></Divider>
          <Divider
            position="absolute"
            top="18.53%"
            bottom="81.36%"
            left="0%"
            right="0%"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Divider[1]")}
          ></Divider>
          <Divider
            position="absolute"
            top="8.29%"
            bottom="91.6%"
            left="0%"
            right="0%"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Divider[2]")}
          ></Divider>
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="137.5px"
            position="absolute"
            top="395px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[1]")}
          >
            <Image
              position="absolute"
              top="0%"
              bottom="5.45%"
              height="94.55%"
              left="0%"
              right="78.02%"
              width="21.98%"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].Image[0]"
              )}
            ></Image>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              position="absolute"
              top="81.45%"
              bottom="1.09%"
              left="29.88%"
              right="39.51%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Order Summary"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(92,102,112,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="23.27%"
              bottom="59.27%"
              left="29.88%"
              right="59.75%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Black"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].Text[1]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="82.55%"
              left="29.88%"
              right="51.85%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Basic Tee"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].Text[2]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(92,102,112,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="46.55%"
              bottom="36%"
              left="29.88%"
              right="59.26%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Large"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].Text[3]"
              )}
            ></Text>
            <MyIcon
              position="absolute"
              top="0%"
              bottom="82.55%"
              left="94.07%"
              right="0%"
              type="delete"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].MyIcon[0]"
              )}
            ></MyIcon>
            <SelectField
              width="64px"
              position="absolute"
              display="flex"
              top="73.09%"
              bottom="0%"
              left="84.2%"
              right="0%"
              placeholder=""
              size="small"
              labelHidden={true}
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[1].SelectField[0]"
              )}
            ></SelectField>
          </View>
          <Divider
            position="absolute"
            top="64.79%"
            bottom="35.1%"
            left="0%"
            right="0%"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Divider[3]")}
          ></Divider>
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="24px"
            position="absolute"
            top="596px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[2]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(48,64,80,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="0%"
              left="0%"
              right="80.8%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Subtotal"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[2].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="right"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="0%"
              left="83.95%"
              right="0%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="$320.00"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[2].Text[1]"
              )}
            ></Text>
          </View>
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="24px"
            position="absolute"
            top="636px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[3]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(48,64,80,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="0%"
              left="0%"
              right="80.21%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Shipping"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[3].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="right"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="0%"
              left="87.16%"
              right="0%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="$15.00"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[3].Text[1]"
              )}
            ></Text>
          </View>
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="24px"
            position="absolute"
            top="676px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[4]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(48,64,80,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="0%"
              left="0%"
              right="86.71%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Taxes"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[4].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="right"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              letterSpacing="0.01px"
              position="absolute"
              top="0%"
              bottom="0%"
              left="86.42%"
              right="0%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="$26.80"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[4].Text[1]"
              )}
            ></Text>
          </View>
          <Divider
            position="absolute"
            top="82.39%"
            bottom="17.49%"
            left="6.82%"
            right="6.82%"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Divider[4]")}
          ></Divider>
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="24px"
            position="absolute"
            top="733px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[5]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              position="absolute"
              top="0%"
              bottom="0%"
              left="0%"
              right="87.6%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Total"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[5].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="right"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              position="absolute"
              top="0%"
              bottom="0%"
              left="83.95%"
              right="0%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="$361.80"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[5].Text[1]"
              )}
            ></Text>
          </View>
          <Divider
            position="absolute"
            top="90.79%"
            bottom="9.09%"
            left="0%"
            right="0%"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Divider[5]")}
          ></Divider>
          <Button
            position="absolute"
            border="1px SOLID rgba(0,0,0,0)"
            borderRadius="4px"
            padding="7px 15px 7px 15px"
            display="flex"
            top="94.71%"
            bottom="0%"
            left="6.82%"
            right="6.82%"
            width="405px"
            backgroundColor="rgba(4,125,149,1)"
            size="large"
            variation="primary"
            children="Place Order"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Button[0]")}
          ></Button>
          <View
            padding="0px 0px 0px 0px"
            width="405px"
            height="24px"
            position="absolute"
            top="105px"
            left="32px"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].View[6]")}
          >
            <MyIcon
              position="absolute"
              top="0px"
              left="0px"
              type="shopping_bag"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[6].MyIcon[0]"
              )}
            ></MyIcon>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="20px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              position="absolute"
              top="0%"
              bottom="16.67%"
              left="9.88%"
              right="74.57%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Cart (2)"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[6].Text[0]"
              )}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="400"
              color="rgba(13,26,38,1)"
              lineHeight="20px"
              textAlign="right"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              position="absolute"
              top="0%"
              bottom="16.67%"
              left="84.44%"
              right="0%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="$101.70"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[1].Flex[0].View[6].Text[1]"
              )}
            ></Text>
          </View>
          <Badge
            color="rgba(54,94,61,1)"
            position="absolute"
            backgroundColor="rgba(214,245,219,1)"
            display="flex"
            top="0px"
            left="32px"
            width="405px"
            fontFamily="Inter"
            fontWeight="700"
            fontSize="14px"
            textAlign="left"
            lineHeight="14px"
            direction="column"
            justifyContent="flex-start"
            size="default"
            variation="success"
            children="Discount - 10% off"
            {...getOverrideProps(overrides, "Flex.Flex[1].Flex[0].Badge[0]")}
          ></Badge>
        </Flex>
      </Flex>
    </Flex>
  );
}
